# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

#gems:         ['jekyll-paginate', 'jekyll-lunr-js-search']
gems:         ['jekyll-paginate']

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"
toc_levels:   1..3 # TOC # 2015/11/29

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#Site config
title: lanpeople-科研小白的成长之路
description: lanpeople's blog
keywords: Deep Learning, Machine Learning, Personal Website
url: https://lanpeoplea.github.io
feed: /atom.xml
favicon: /resources/images/龙肖.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 实用链接
    url: /links.html
  - text: 更多
    url: /about.html

#Author config
author:
    name: lanpeople
    email: lanpeople326@gmail.com
    imageLink: /resources/images/039.jpg
    simpleIntro: 终身学习者
    detailIntro: UESTC 软件工程硕士，研究机器学习、深度学习。热爱长跑、马拉松。

#You can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-github-alt
    url: https://github.com/LanPeoplea

#Links
customLinks:
  - item:
    - text: IEEE Xplore
      url: https://ieeexplore.ieee.org/Xplore/home.jsp
    - text: arXiv.org
      url: https://arxiv.org/
    - text: Sci-Hub
      url: https://www.sci-hub.ren/
    - text: LetPub：查看期刊分区
      url: https://www.letpub.com.cn/index.php?page=journalapp&view=search
    - text: IGG谷歌访问助手
      url: https://iguge.xyz/
    message: 科研必备
  - item:
    - text: 动手学深度学习（网站）
      url: https://zh-v2.d2l.ai/
    - text: 动手学深度学习（PyTorch版）
      url: /resources/books/d2l-zh-pytorch.pdf
    - text: 动手学CV-Pytorch
      url: https://datawhalechina.github.io/dive-into-cv-pytorch/#/
    - text: Deep Learning（网站）
      url: https://www.deeplearningbook.org/
    - text: Deep Learning中文版
      url: /resources/books/dlbook_cn_v0.5-beta.pdf
    - text: 神经网络与深度学习-邱锡鹏（网站）
      url: https://nndl.github.io/
    - text: 人工智能领域基础概念和术语
      url: https://github.com/jiqizhixin/Artificial-Intelligence-Terminology-Database
    message: 机器学习
  - item:
    - text: 阿里巴巴矢量图标库
      url: https://www.iconfont.cn/
    message: 素材库
  - item:
    - text: IPAdress
      url: https://www.ipaddress.com/
    - text: 嗯哩嗯哩
      url: https://www.enlienli.com/
    - text: 剧嗨影院
      url: https://www.juhi.cc/
    - text: 努努影院
      url: https://www.nunuyy.cc/
    - text: 天猫影院
      url: http://www.tmaotv.com/
    - text: 捷华影视
      url: https://www.jiehua.tv/
    - text: 555电影
      url: https://www.o8tv.com/
    - text: 牛视网
      url: https://www.chaojidianshi.net/
    - text: Healer的工具箱
      url: https://tool.yijingying.com/
    - text: 在线音乐
      url: http://tool.ooopn.com/Tools/vipmusic/
    - text: Tonzhon Lite
      url: http://lite.tonzhon.com/
    message: Resource


googleAnaly:
  config: false
  id: UA-58146229-1

#baidu tongji
baiduTongji:
  config: true
  id:  9144251ce5a4f4019de4bc601b9b490b

#comment config
disqus:
  config: true
  id: LanPeoplea

duoshuo:
  config: false
  id: null

#baidu share config
baiduShare:
  config: false

# lunr search
lunr_search:
  excludes: [rss.xml, atom.xml]
  stopwords: "stopwords.txt"
  min_length: 3
  js_dir: "javascript"
